on: push
name: Validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: desaintmartin/helm-kubeval-action@master
      with:
        path: ./helm/opendistro-es
